# Generated by Django 4.0.4 on 2022-05-18 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=50)),
                ('answer_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('question_text', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Results_of_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_severity_index', models.FloatField()),
                ('positive_symptom_total', models.FloatField()),
                ('somatization_p', models.FloatField()),
                ('obsessive_compulsion_p', models.FloatField()),
                ('interpersonal_sensitivity_p', models.FloatField()),
                ('depression_p', models.FloatField()),
                ('anxiety_p', models.FloatField()),
                ('hostility_p', models.FloatField()),
                ('phobic_anxiety_p', models.FloatField()),
                ('paranoid_ideation_p', models.FloatField()),
                ('psychoticism_p', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
