# Generated by Django 4.0.4 on 2022-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
    ]
