# Generated by Django 4.0.4 on 2022-05-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdi', '0003_alter_answers_question_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
