# Generated by Django 4.0.4 on 2022-05-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdi', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
